# Creating dict for quick output layer lookup

In [54]:
import os

# absolute path to raw-data dir
raw_data_path = r"../dataset/raw-data/"

# creating an array of directory names
raw_data_dir = os.listdir(raw_data_path)

# creating a dictionary where the key is a directory name, and the value is an array which represents output layer output 
dir_dict = {}

for i in range(len(raw_data_dir)):
    output_arr = [0] * len(raw_data_dir)
    output_arr[i] = 1

    dir_dict[raw_data_dir[i]] = output_arr

In [85]:
print(dir_dict)

{'Raspberry___healthy': [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Background_without_leaves': [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Tomato___healthy': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Potato___Early_blight': [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Corn___healthy': [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Corn___Common_rust': [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'Strawberry___Leaf_scorch': [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], '

# Creating image and output arrays

In [77]:
import os

image_arr = []
label_arr = []

# absolute path to raw-data dir
raw_data_path = r"../dataset/raw-data/"

# looping through every image in raw-data and creating two arrays, with every index holding a numpy array of images
# and the other holding labels at the same index
for dirpath, dirnames, filenames in os.walk(raw_data_path):
    # skip hidden directories
    dirnames[:] = [dirname for dirname in dirnames if not dirname.startswith('.')]
    
    # iterate over filenames and check if they end with .img
    for file in filenames:
        if file.endswith('.JPG'):
            name_disease = os.path.basename(dirpath)
            image_arr.append(file)
            label_arr.append(dir_dict[name_disease])

In [82]:
with Image.open(image_path) as img:
        # Convert the image to a NumPy array
        image_array = np.array(img)
        print("Image loaded successfully!")
        print("Image shape:", image_array.shape) 

ValueError: invalid literal for int() with base 10: 'image (59).JPG'

### [TESTING] just need to update image path

In [102]:
import os
import numpy as np

image_arr = []
label_arr = []

# absolute path to raw-data dir
raw_data_path = r"../dataset/raw-data/"

# looping through every image in raw-data and creating two arrays, with every index holding a numpy array of images
# and the other holding labels at the same index
for dirpath, dirnames, filenames in os.walk(raw_data_path):
    # skip hidden directories
    dirnames[:] = [dirname for dirname in dirnames if not dirname.startswith('.')]
    
    # iterate over filenames and check if they end with .img
    for file in filenames:
        if file.endswith('.JPG'):
            with Image.open(f"{dirpath}/{file}") as img:
                image_as_array = np.array(img)
                
            name_disease = os.path.basename(dirpath)
            
            image_arr.append(image_as_array)
            label_arr.append(dir_dict[name_disease])

In [103]:
print(image_arr[0])

[[[178 173 179]
  [200 195 201]
  [193 188 194]
  ...
  [139 127 131]
  [152 140 144]
  [134 122 126]]

 [[205 200 206]
  [181 176 182]
  [186 181 187]
  ...
  [137 125 129]
  [147 135 139]
  [131 119 123]]

 [[198 193 199]
  [160 155 161]
  [180 175 181]
  ...
  [139 127 131]
  [147 135 139]
  [135 123 127]]

 ...

 [[201 195 197]
  [202 196 198]
  [202 196 198]
  ...
  [172 160 162]
  [170 158 160]
  [164 152 154]]

 [[196 190 192]
  [200 194 196]
  [204 198 200]
  ...
  [162 150 152]
  [157 145 147]
  [148 136 138]]

 [[196 190 192]
  [202 196 198]
  [208 202 204]
  ...
  [173 161 163]
  [168 156 158]
  [158 146 148]]]


# [TESTING] making image path

In [100]:
import os

image_arr = []
label_arr = []

# absolute path to raw-data dir
raw_data_path = r"../dataset/raw-data/"

# looping through every image in raw-data and creating two arrays, with every index holding a numpy array of images
# and the other holding labels at the same index
for dirpath, dirnames, filenames in os.walk(raw_data_path):
    # skip hidden directories
    dirnames[:] = [dirname for dirname in dirnames if not dirname.startswith('.')]
    
    # iterate over filenames and check if they end with .img
    for file in filenames:
        if file.endswith('.JPG'):
            name_disease = os.path.basename(dirpath)
            image_arr.append(file)
            label_arr.append(dir_dict[name_disease])

            print(f"{dirpath}/{file}")

../dataset/raw-data/Raspberry___healthy/image (59).JPG
../dataset/raw-data/Raspberry___healthy/image (283).JPG
../dataset/raw-data/Raspberry___healthy/image (170).JPG
../dataset/raw-data/Raspberry___healthy/image (233).JPG
../dataset/raw-data/Raspberry___healthy/image (89).JPG
../dataset/raw-data/Raspberry___healthy/image (131).JPG
../dataset/raw-data/Raspberry___healthy/image (270).JPG
../dataset/raw-data/Raspberry___healthy/image (302).JPG
../dataset/raw-data/Raspberry___healthy/image (304).JPG
../dataset/raw-data/Raspberry___healthy/image (76).JPG
../dataset/raw-data/Raspberry___healthy/image (243).JPG
../dataset/raw-data/Raspberry___healthy/image (316).JPG
../dataset/raw-data/Raspberry___healthy/image (85).JPG
../dataset/raw-data/Raspberry___healthy/image (306).JPG
../dataset/raw-data/Raspberry___healthy/image (46).JPG
../dataset/raw-data/Raspberry___healthy/image (57).JPG
../dataset/raw-data/Raspberry___healthy/image (250).JPG
../dataset/raw-data/Raspberry___healthy/image (160).JP

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

